env:
  global:
    - CC_TEST_REPORTER_ID=2a7e6b56ff86df652bbe1ae052dea5b16b634dde19e70e07ec9102684d84ec0a
language: node_js
node_js:
  - "8"
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info